FROM php:8.3-fpm

# 必要な拡張
RUN apt-get update && apt-get install -y \
    zip unzip git libpq-dev libzip-dev libpng-dev \
    && docker-php-ext-install pdo_mysql zip gd

# composer install
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
ENV PATH="/usr/bin:$PATH"


WORKDIR /var/www/html
