FROM php:8.3-fpm

# 必須拡張とツールのインストール
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        zip unzip git libpq-dev libzip-dev libpng-dev zlib1g-dev \
    && docker-php-ext-install pdo_mysql zip gd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# composer インストール
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
ENV PATH="/usr/bin:$PATH"

WORKDIR /var/www/html
