FROM nginx:1.25-alpine

# Nginx 設定をコピー
COPY default.conf /etc/nginx/conf.d/default.conf

# Laravel（PHP）と Next.js（Node）のログを見やすくする
RUN mkdir -p /var/log/nginx \
    && touch /var/log/nginx/access.log \
    && touch /var/log/nginx/error.log

# 権限調整（Alpine の場合は必要）
RUN chmod -R 755 /var/log/nginx

EXPOSE 80
